# Configuration for the cryptography jars that need to be installed in the Tomcat isntance

---
local_policy_url: http://gka-nexus.postofficefot.eu-gb.mybluemix.net/local-policy-7.0.jar
us_export_policy: http://gka-nexus.postofficefot.eu-gb.mybluemix.net/us-export-policy-7.0.jar